### ISSUE TITLE
What it means "call of reflect.Value.Interface on zero Value"

### ISSUE THREAD

**Issue by rubiagatra** [softbrewery/gojoi#1]
Do you have any idea when I got error "call of reflect.Value.Interface on zero Value" ?

**Comment by stevenceuppens** [comment]
Hi @rubiagatra can you share your schema?

**Comment by rubiagatra** [comment]
Thank you for your response and your hard work @stevenceuppens to Gojoi. Unfortunately, I already use an alternative, it is https://github.com/go-ozzo/ozzo-validation
